/* eslint-disable */
require('./arrow-up')
require('./boxes')
require('./calendar')
require('./clock')
require('./close-circle')
require('./comment')
require('./edit')
require('./facebook')
require('./file')
require('./google')
require('./hand-holding-usd')
require('./money-bill')
require('./people')
require('./search')
require('./shopping-cart')
require('./star')
require('./wordpress')
